module Arcadia.Tio
  ( module Arcadia.Tio.Error
  , module Arcadia.Tio.Types
  , module Arcadia.Tio.Tensor
  , NativeLibrary
  , expectedAbiVersion
  , nativeLibraryPath
  , loadNativeLibrary
  , loadNativeLibraryFrom
  , resolveNativeLibraryPath
  , abiVersion
  , lastError
  , TensorFile
  , AppendRange(..)
  , ArrowCData
  , arrowArrayLength
  , arrowSchemaFormat
  , releaseArrowCData
  , createStreaming
  , createStreamingWithMetadata
  , createStreamingWithCoordinates
  , createRandomAccessWithCoordinates
  , createInferredWithCoordinates
  , createWithPolicyWithCoordinates
  , createStreamingWithCoordinatesV2
  , createRandomAccessWithCoordinatesV2
  , createInferredWithCoordinatesV2
  , createWithPolicyWithCoordinatesV2
  , createStreamingWithUniverse
  , createRandomAccessWithUniverse
  , createWithPolicyWithUniverse
  , createRandomAccess
  , createRandomAccessWithMetadata
  , createInferred
  , createInferredWithMetadata
  , createWithPolicy
  , createWithPolicyWithMetadata
  , open
  , close
  , rank
  , dtype
  , appendAxis
  , dimLens
  , chunkPlan
  , filePath
  , loadMeta
  , coordinateMeta
  , loadCoordinateMeta
  , coordinateMetaV2
  , loadCoordinateMetaV2
  , readAxisCoordinates
  , readAxisCoordinatesV2
  , coordinateDictionaryV2
  , coordinateLookupV2
  , coordinateLookupRangeV2
  , setDimName
  , setSymbols
  , setChannels
  , setUserKv
  , setCompressionConfig
  , getCompressionConfig
  , headCommit
  , listCommits
  , pop
  , popBatched
  , revertCommit
  , readAtCommit
  , readAtCommitSelected
  , readAtCommitDense
  , readAtCommitDenseSelected
  , readWithOptions
  , readWithOptionsDense
  , readWithShapePolicy
  , readWithShapePolicyDense
  , readWithOptionsAttributed
  , readWithOptionsDenseAttributed
  , readAtCommitWithOptions
  , readAtCommitWithOptionsDense
  , readAtCommitWithShapePolicy
  , readAtCommitWithShapePolicyDense
  , readIndex
  , getIndexCheckpointEveryCommits
  , setIndexCheckpointEveryCommits
  , analyzeCompaction
  , analyzeV4Compaction
  , analyzeV4CompactionPrecise
  , compactTo
  , compactV4RetainedHistoryTo
  , compactV4RetainedHistoryToPrecise
  , reformTo
  , reformToEx
  , maybeCompact
  , getAutoCompactionConfig
  , setAutoCompactionConfig
  , compactionState
  , maybeCompactAuto
  , v4Diagnostics
  , v4DiagnosticsPrecise
  , analyzeSparseAppend
  , analyzeSparseAppendF32
  , analyzeSparseAppendF64
  , analyzeSparseAppendI32
  , analyzeSparseAppendI64
  , appendSparse
  , appendSparseF32
  , appendSparseF64
  , appendSparseI32
  , appendSparseI64
  , appendDense
  , appendDenseF32
  , appendDenseF64
  , appendDenseI32
  , appendDenseI64
  , appendDenseWithCoordinatesV2
  , appendDenseF32WithCoordinatesV2
  , appendDenseF64WithCoordinatesV2
  , appendDenseI32WithCoordinatesV2
  , appendDenseI64WithCoordinatesV2
  , appendDenseWithUniverse
  , appendDenseF32WithUniverse
  , appendDenseF64WithUniverse
  , appendDenseI32WithUniverse
  , appendDenseI64WithUniverse
  , readAll
  , readAllAs
  , readAllF32
  , readAllF64
  , readAllI32
  , readAllI64
  , readAllDense
  , readAllDenseAs
  , readAllDenseF32
  , readAllDenseF64
  , readAllDenseI32
  , readAllDenseI64
  , readAxisRange
  , readAxisTake
  , readAxisOne
  , readEntryRange
  , takeEntries
  , readScalar
  , rewriteF32
  , rewriteF64
  , rewriteSliceF32
  , rewriteSliceF64
  , clearBlocks
  , readValuesArrow
  ) where

import Arcadia.Tio.Error
import Arcadia.Tio.Internal.CApi
  ( NativeLibrary
  , abiVersion
  , expectedAbiVersion
  , lastError
  , loadNativeLibrary
  , loadNativeLibraryFrom
  , nativeLibraryPath
  , resolveNativeLibraryPath
  )
import Arcadia.Tio.Tensor
import Arcadia.Tio.TensorFile
import Arcadia.Tio.Types
